version: "3.9"

services:

  jenkins:
    build: .
    container_name: jenkins
    env_file: env.txt
    restart: unless-stopped
    ports:
    - "127.0.0.1:8080:8080"
    - "127.0.0.1:50000:50000"
    volumes:
      - jenkins_vol:/var/run/jenkins_home
volumes:
  jenkins_vol:
